title: Carter M Parker Blog
description: Posts by Carter Parker
remote_theme: mmistakes/minimal-mistakes@4.27.1
minimal_mistakes_skin: "air"

plugins:
  - jekyll-include-cache
  
author:
  name: Carter Parker
  avatar: "/assets/images/me.jpg"
  bio: "Writing about autism, fitness, politics, whatever else"
  location: "Long Island"
  links:
    - label: "X"
      icon: "fa-brands fa-x-twitter"
      url: https://x.com/cartermparker
    - label: "Insta"
      icon: "fa-brands fa-instagram"
      url: https://instagram.com/C4rt3r824

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true

sass:
  sass_dir: assets/css